apiVersion: v1
kind: Pod
metadata:
  name: alpine-1000
spec:
  containers:
  - name: alpine-1000
    image: jondkelley/nonroot_alpine_tools
    command:
    - 'sleep'
    - '1000'
    securityContext:
      runAsUser: 1000
      #redundant as 1000 is not root but good to have
      #as the runtime will do verification that no process will
      #run as root within the container
      runAsNonRoot: true
